import { useEffect, useMemo, useRef, useState } from 'react';
import { trackCopy, trackDownload, trackToolUse } from '../../lib/analytics';
import { calculateEndTime, formatHashtags, progressValues, randomItem } from '../../lib/vtuber';
import VtuberNameChecker from './VtuberNameChecker';

type Props = { id: string };
const copy = async (id: string, value: string) => { if (!value) return; await navigator.clipboard.writeText(value); trackCopy(id); };

function TitleGenerator() {
  const [game, setGame] = useState(''); const [content, setContent] = useState(''); const [mood, setMood] = useState('まったり');
  const [beginner, setBeginner] = useState(true); const [participation, setParticipation] = useState(false); const [results, setResults] = useState<string[]>([]);
  const generate = () => { const subject = [game, content].filter(Boolean).join('｜') || '今日の配信'; const flags = [beginner && '初見歓迎', participation && '参加型'].filter(Boolean).join('・'); const next = [`【${flags || mood}】${subject}！${mood}配信`, `${subject}｜${mood}に楽しむ${flags ? `【${flags}】` : ''}`, `【配信】${subject} ${flags || mood}`]; setResults(next.sort(() => Math.random() - .5)); trackToolUse('stream-title-generator', 'generate'); };
  return <div className="generator-grid"><div className="field-stack"><label>ゲーム名<input value={game} onChange={e=>setGame(e.target.value)} placeholder="例：Minecraft" /></label><label>配信内容<input value={content} onChange={e=>setContent(e.target.value)} placeholder="例：新しい街を作る" /></label><label>雰囲気<select value={mood} onChange={e=>setMood(e.target.value)}><option>まったり</option><option>元気</option><option>深夜</option><option>初心者</option><option>ガチ挑戦</option></select></label><label className="check-field"><input type="checkbox" checked={beginner} onChange={e=>setBeginner(e.target.checked)} /> 初見歓迎</label><label className="check-field"><input type="checkbox" checked={participation} onChange={e=>setParticipation(e.target.checked)} /> 参加型</label><button className="button primary" onClick={generate}>タイトル候補を生成</button></div><ResultList id="stream-title-generator" results={results} empty="入力してタイトル候補を生成してください" /></div>;
}

function ResultList({ id, results, empty }: { id:string; results:string[]; empty:string }) { return <div className="result-list" aria-live="polite">{results.length ? results.map((value,i)=><div key={`${value}-${i}`}><span>{value}</span><button onClick={()=>copy(id,value)}>コピー</button></div>) : <p className="empty-result">{empty}</p>}</div>; }

function AnnouncementGenerator() {
  const [title,setTitle]=useState(''); const [date,setDate]=useState(''); const [url,setUrl]=useState(''); const [tags,setTags]=useState(''); const [note,setNote]=useState(''); const [results,setResults]=useState<string[]>([]);
  const generate=()=>{if(!title.trim()){setResults([]);return;} const tagText=formatHashtags(tags,' '); const base=[title,date&&`📅 ${date}`,url,tagText].filter(Boolean).join('\n'); setResults([`📢 配信のお知らせ\n${base}\n${note}`.trim(),`このあと配信！\n${base}\n遊びに来てね！`.trim(),`${note||'配信します！'}\n\n${base}`]);trackToolUse('stream-announcement-generator','generate')};
  return <div className="generator-grid"><div className="field-stack"><label>配信タイトル<input value={title} onChange={e=>setTitle(e.target.value)} /></label><label>配信日時<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)} /></label><label>配信URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." /></label><label>ハッシュタグ<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="配信タグ VTuber" /></label><label>一言<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} /></label><button className="button primary" onClick={generate}>告知文を生成</button></div><div className="result-list">{results.length?results.map((value,i)=><div className="announcement" key={i}><span>{value}</span><small>{Array.from(value).length}文字</small><button onClick={()=>copy('stream-announcement-generator',value)}>コピー</button></div>):<p className="empty-result">配信タイトルを入力してください</p>}</div></div>;
}

const days=['月','火','水','木','金','土','日'];
function ScheduleMaker(){const [rows,setRows]=useState(days.map(day=>({day,time:'20:00',title:'',detail:''})));const [theme,setTheme]=useState('night');const canvas=useRef<HTMLCanvasElement>(null);const draw=()=>{const c=canvas.current;if(!c)return;const x=c.getContext('2d');if(!x)return;const themes={night:['#111827','#60a5fa'],pink:['#fff1f2','#e11d48'],mint:['#ecfdf5','#047857']} as const;const [bg,accent]=themes[theme as keyof typeof themes];x.fillStyle=bg;x.fillRect(0,0,1200,675);x.fillStyle=accent;x.font='bold 52px sans-serif';x.fillText('WEEKLY STREAM SCHEDULE',60,78);rows.forEach((r,i)=>{const y=128+i*70;x.fillStyle=i%2?'rgba(255,255,255,.06)':'rgba(255,255,255,.12)';x.fillRect(50,y-40,1100,58);x.fillStyle=theme==='night'?'#fff':'#172033';x.font='bold 26px sans-serif';x.fillText(`${r.day}  ${r.time}`,72,y);x.font='22px sans-serif';x.fillText(`${r.title || '配信予定なし'}  ${r.detail}`,280,y)});trackToolUse('stream-schedule-maker','preview')};useEffect(draw,[rows,theme]);const download=()=>{const a=document.createElement('a');a.href=canvas.current?.toDataURL('image/png')||'';a.download='stream-schedule.png';a.click();trackDownload('stream-schedule-maker','png')};return <div className="schedule-layout"><div className="field-stack"><label>テーマ<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="night">ナイトブルー</option><option value="pink">ライブピンク</option><option value="mint">ミント</option></select></label>{rows.map((r,i)=><div className="schedule-row" key={r.day}><b>{r.day}</b><input type="time" value={r.time} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,time:e.target.value}:v))}/><input placeholder="タイトル" value={r.title} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,title:e.target.value}:v))}/><input placeholder="内容" value={r.detail} onChange={e=>setRows(rows.map((v,n)=>n===i?{...v,detail:e.target.value}:v))}/></div>)}<button className="button primary" onClick={download}>PNGをダウンロード</button></div><canvas ref={canvas} width="1200" height="675" className="schedule-canvas" /></div>}

function ThumbnailResizer(){const [image,setImage]=useState<HTMLImageElement|null>(null);const [mode,setMode]=useState<'crop'|'contain'>('crop');const [format,setFormat]=useState<'image/png'|'image/jpeg'>('image/jpeg');const canvas=useRef<HTMLCanvasElement>(null);const load=(file?:File)=>{if(!file?.type.startsWith('image/'))return;const u=URL.createObjectURL(file);const img=new Image();img.onload=()=>{setImage(img);URL.revokeObjectURL(u)};img.src=u};useEffect(()=>{const c=canvas.current;if(!c||!image)return;const x=c.getContext('2d');if(!x)return;x.fillStyle='#fff';x.fillRect(0,0,1280,720);const scale=mode==='crop'?Math.max(1280/image.width,720/image.height):Math.min(1280/image.width,720/image.height);const w=image.width*scale,h=image.height*scale;x.drawImage(image,(1280-w)/2,(720-h)/2,w,h)},[image,mode]);const download=()=>{const a=document.createElement('a');a.href=canvas.current?.toDataURL(format,.9)||'';a.download=`youtube-thumbnail.${format==='image/png'?'png':'jpg'}`;a.click();trackDownload('youtube-thumbnail-resizer',format)};return <div className="image-layout"><label className="dropzone"><input type="file" accept="image/*" onChange={e=>load(e.target.files?.[0])}/><span className="upload-icon">↑</span><strong>画像を選択</strong><small>画像は外部へ送信されません</small></label>{image&&<div className="field-stack"><div className="toolbar wrap"><label>調整方法<select value={mode} onChange={e=>setMode(e.target.value as 'crop'|'contain')}><option value="crop">中央トリミング</option><option value="contain">余白を追加</option></select></label><label>形式<select value={format} onChange={e=>setFormat(e.target.value as 'image/png'|'image/jpeg')}><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label><button className="button primary" onClick={download}>1280×720でダウンロード</button></div><canvas ref={canvas} width="1280" height="720" className="schedule-canvas" /></div>}</div>}

function Countdown(){const [minutes,setMinutes]=useState(5);const [seconds,setSeconds]=useState(0);const [left,setLeft]=useState(300);const [running,setRunning]=useState(false);const box=useRef<HTMLDivElement>(null);useEffect(()=>{if(!running)return;const timer=setInterval(()=>setLeft(v=>{if(v<=1){setRunning(false);return 0}return v-1}),1000);return()=>clearInterval(timer)},[running]);const reset=()=>{setRunning(false);setLeft(Math.max(0,minutes*60+seconds))};const label=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;return <div className="countdown-wrap" ref={box}><div className="countdown-display">{label}</div><div className="countdown-controls"><label>分<input type="number" min="0" max="999" value={minutes} onChange={e=>setMinutes(Math.max(0,+e.target.value))}/></label><label>秒<input type="number" min="0" max="59" value={seconds} onChange={e=>setSeconds(Math.min(59,Math.max(0,+e.target.value)))}/></label></div><div className="button-row"><button className="button primary" onClick={()=>{setRunning(true);trackToolUse('obs-countdown','start')}}>開始</button><button className="button" onClick={()=>setRunning(false)}>一時停止</button><button className="button" onClick={reset}>リセット</button><button className="button" onClick={()=>box.current?.requestFullscreen()}>全画面</button></div></div>}

const ideas:Record<string,string[]>={ゲーム:['初見ゲームを1時間で攻略','視聴者参加型で協力プレイ','縛りルールでボス挑戦'],雑談:['最近買ってよかったもの10選','視聴者の質問に即答','失敗談から学んだこと'],歌:['テーマ限定歌枠','リクエスト候補からルーレット','年代別メドレー'],チャレンジ:['目標達成まで終われない','利き○○チャレンジ','制限時間で作品づくり']};
function IdeaGenerator(){const [genre,setGenre]=useState('ゲーム');const [result,setResult]=useState('');const generate=()=>{setResult(randomItem(ideas[genre]));trackToolUse('stream-idea-generator','generate')};return <RandomPanel label="配信ジャンル" value={genre} setValue={setGenre} options={Object.keys(ideas)} result={result} generate={generate} />}
const topics:Record<string,string[]>={日常:['今日いちばん嬉しかったことは？','最近変えた小さな習慣は？'],ゲーム:['初めて夢中になったゲームは？','ゲーム世界で暮らすならどこ？'],食べ物:['一生ひとつだけ食べるなら？','地元のおすすめ料理は？'],恋愛:['理想のデートプランは？','友情から恋に変わる瞬間は？'],趣味:['時間を忘れる趣味は？','新しく始めたいことは？'],思い出:['子どもの頃の宝物は？','忘れられない旅行は？'],季節:['好きな季節の過ごし方は？','今年やりたい季節イベントは？'],'VTuber活動':['配信を始めたきっかけは？','今後挑戦したい配信は？']};
function TalkGenerator(){const [genre,setGenre]=useState('日常');const [result,setResult]=useState('');const generate=()=>{setResult(randomItem(topics[genre]));trackToolUse('talk-topic-generator','generate')};return <RandomPanel label="カテゴリ" value={genre} setValue={setGenre} options={Object.keys(topics)} result={result} generate={generate} />}
function RandomPanel({label,value,setValue,options,result,generate}:{label:string,value:string,setValue:(v:string)=>void,options:string[],result:string,generate:()=>void}){return <div className="random-panel"><label>{label}<select value={value} onChange={e=>setValue(e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label><div className="random-result" aria-live="polite">{result||'ボタンを押してお題を表示'}</div><button className="button primary" onClick={generate}>ランダム生成</button></div>}

function TimeCalculator(){const today=new Date().toISOString().slice(0,10);const [date,setDate]=useState(today);const [time,setTime]=useState('20:00');const [hours,setHours]=useState(2);const [minutes,setMinutes]=useState(0);const result=calculateEndTime(date,time,hours,minutes);const formatted=result?new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(result):'入力内容を確認してください';return <div className="calculator-panel"><div className="input-grid"><label>開始日<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>開始時刻<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>予定時間<input type="number" min="0" max="168" value={hours} onChange={e=>setHours(+e.target.value)}/></label><label>追加分<input type="number" min="0" max="59" value={minutes} onChange={e=>setMinutes(+e.target.value)}/></label></div><div className="calculation-result"><span>終了予定</span><strong>{formatted}</strong></div></div>}

function HashtagFormatter(){const [input,setInput]=useState('');const [separator,setSeparator]=useState<'\n'|' '>('\n');const result=useMemo(()=>formatHashtags(input,separator),[input,separator]);return <div className="generator-grid"><div className="field-stack"><label>単語・タグ<textarea rows={10} value={input} onChange={e=>setInput(e.target.value)} placeholder={'配信タグ\nVTuber  配信タグ'}/></label><label>出力区切り<select value={separator==='\n'?'line':'space'} onChange={e=>setSeparator(e.target.value==='line'?'\n':' ')}><option value="line">改行</option><option value="space">スペース</option></select></label></div><div className="field-stack"><label>整形結果<textarea rows={10} readOnly value={result}/></label><button className="button primary" disabled={!result} onClick={()=>copy('hashtag-formatter',result)}>コピー</button></div></div>}

function GoalCounter(){const [goal,setGoal]=useState(1000);const [current,setCurrent]=useState(350);const values=progressValues(current,goal);const pct=values?.percentage??0;return <div className="goal-panel"><div className="input-grid"><label>目標値<input type="number" min="1" value={goal} onChange={e=>{setGoal(+e.target.value);trackToolUse('stream-goal-counter','input')}}/></label><label>現在値<input type="number" min="0" value={current} onChange={e=>setCurrent(+e.target.value)}/></label></div>{values?<><div className="goal-numbers"><div><span>達成率</span><strong>{pct.toFixed(1)}%</strong></div><div><span>残り</span><strong>{values.remaining.toLocaleString()}</strong></div></div><div className="progress-track" role="progressbar" aria-valuenow={Math.min(100,pct)} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${Math.min(100,pct)}%`}}/></div></>:<p className="message error">目標値は1以上、現在値は0以上で入力してください。</p>}</div>}

export default function VtuberTool({id}:Props){switch(id){case'name-checker':return <VtuberNameChecker/>;case'stream-title-generator':return <TitleGenerator/>;case'stream-announcement-generator':return <AnnouncementGenerator/>;case'stream-schedule-maker':return <ScheduleMaker/>;case'youtube-thumbnail-resizer':return <ThumbnailResizer/>;case'obs-countdown':return <Countdown/>;case'stream-idea-generator':return <IdeaGenerator/>;case'talk-topic-generator':return <TalkGenerator/>;case'stream-time-calculator':return <TimeCalculator/>;case'hashtag-formatter':return <HashtagFormatter/>;case'stream-goal-counter':return <GoalCounter/>;default:return null}}
